name: Summarize Reward Field
on:
  schedule:
    - cron: "0 0 1 * *" # Run at 00:00 on the first day of every month

jobs:
  summarize-reward-field:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check for new commits since last summary
        run: |
          last_tag=$(git describe --tags --abbrev=0 --match "summary-*")

          if [ -z "$last_tag" ]; then
            echo "No previous summary tags found."
            echo "NEW_COMMITS=true" >> $GITHUB_ENV
          else
            new_commits=$(git log $last_tag..HEAD --oneline)
            if [ -z "$new_commits" ]; then
              echo "No new commits since last summary tag."
              echo "NEW_COMMITS=false" >> $GITHUB_ENV
            else
              echo "New commits found."
              echo "NEW_COMMITS=true" >> $GITHUB_ENV
            fi
          fi
      - name: Get reward data of last month from tags
        if: env.NEW_COMMITS == 'true'
        run: |
          last_month=$(date -d "$(date +%Y-%m-01) -1 month" +%Y-%m)
          git tag --list "reward-*" --format="%(refname:short) %(creatordate:short)" | \
          awk -v last_month="$last_month" '$2 >= last_month {print $1}' > reward_tags.txt

          while IFS= read -r tag; do
            git show $tag:reward_output.yml >> all_rewards.yml
          done < reward_tags.txt

      - name: Summarize rewards
        if: env.NEW_COMMITS == 'true'
        run: cat all_rewards.yml | deno run --allow-read ./scripts/count-reward.ts > summary.yml

      - name: Save Summary in Git tag
        if: env.NEW_COMMITS == 'true'
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          tag_name="summary-$(date +%Y-%m)"

          git tag -a $tag_name $(git rev-parse HEAD) -m "$(cat summary.yml)"
          git push origin --tags

      - name: Save Summary in GitHub release
        if: env.NEW_COMMITS == 'true'
        run: |
          gh release create $tag_name --notes "$(cat summary.yml)"
